"""Independent calibration checkpoints, covariance, and source preservation."""

import csv
import hashlib
import json
from pathlib import Path, PureWindowsPath
from types import SimpleNamespace

import numpy as np
import pytest
from scipy.integrate import quad

from scripts.check_numerical_archive import check_rows
from scripts.reconstruct_miozzi_2020_iron import (
    MODELS,
    OUT,
    PUBLISHED,
    ROOT,
    R,
    conditional_covariance,
    constant_q_gamma_theta,
    debye_energy,
    derivative,
    effective_sigma,
    fe_pressure,
    mgo_gamma_theta,
    mgo_pressure,
    pressure_column,
    read_data,
    reconstruct,
)


def test_source_fingerprints_use_portable_paths_on_windows(monkeypatch):
    path_type = type(Path())
    original_relative_to = path_type.relative_to

    def windows_relative_to(path, *parts, **kwargs):
        return PureWindowsPath(original_relative_to(path, *parts, **kwargs))

    _, _, expected = read_data()
    with monkeypatch.context() as context:
        context.setattr(path_type, "relative_to", windows_relative_to)
        _, _, actual = read_data()
    assert actual == expected
    assert all("\\" not in name for name in actual)


def test_dorogokupets_independent_published_pressure_checkpoints():
    # Values printed in the 2010 paper, not generated by this script.
    name = "dorogokupets_2010_fit2_einstein"
    volume = np.array([1, 0.85, 0.64]) * MODELS[name]["V0_a3"]
    np.testing.assert_allclose(
        mgo_pressure(volume, [3000, 3000, 3663], name),
        [17.69, 54.21, 203.34],
        atol=0.005,
        rtol=0,
    )


@pytest.mark.parametrize("name", MODELS)
def test_calibration_reference_and_integrated_thermodynamic_identity(name):
    m = MODELS[name]
    assert mgo_pressure(
        m["V0_a3"], m["reference_temperature_k"], name
    ) == pytest.approx(0, abs=1e-12)
    volume = np.array([0.65, 0.8, 1]) * m["V0_a3"]
    gamma, _ = mgo_gamma_theta(volume, name)
    h = 1e-5
    log_derivative = -(
        np.log(mgo_gamma_theta(volume * np.exp(h), name)[1])
        - np.log(mgo_gamma_theta(volume * np.exp(-h), name)[1])
    ) / (2 * h)
    np.testing.assert_allclose(log_derivative, gamma, rtol=1e-8)


def test_quadrature_against_adaptive_integral_and_q_zero_limit():
    name = "speziale_variable_q_debye"
    m = MODELS[name]
    ratio = 0.65
    integral = quad(
        lambda u: m["gamma0"] * np.exp(m["q0"] / m["q1"] * np.expm1(m["q1"] * u)),
        0,
        np.log(ratio),
        epsabs=1e-12,
    )[0]
    theta = mgo_gamma_theta(ratio * m["V0_a3"], name)[1]
    assert theta == pytest.approx(773 * np.exp(-integral), rel=1e-12)
    limit = theta / 1400
    expected = (
        18 * R * 1400 / limit**3 * quad(lambda x: x**3 / np.expm1(x), 0, limit)[0]
    )
    assert debye_energy(theta, 1400, 2) == pytest.approx(expected, rel=1e-12)
    for q in (0, 1e-10, -1e-10):
        gamma, theta = constant_q_gamma_theta(np.array([0.7, 1]), 1.11, q, 420)
        np.testing.assert_allclose(gamma, 1.11, rtol=1e-9)
        np.testing.assert_allclose(
            theta, 420 * np.array([0.7, 1]) ** (-1.11), rtol=1e-9
        )


def test_shared_temperature_variance_and_source_error_preservation():
    _, data, _ = read_data()
    index = np.flatnonzero(data["mgo"] & (data["temperature_k"] > 300))[0]
    one = {k: v[index : index + 1].copy() for k, v in data.items()}
    one["volume_error_a3"][:] = 0
    one["mgo_volume_error_a3"][:] = 0
    one["pressure_error_gpa"][:] = 1e6  # Must not be reused after reconstruction.
    name = "speziale_variable_q_debye"
    _, _, pt = pressure_column(one, name)
    ft = derivative(
        lambda t: fe_pressure(one["volume_a3"], t, PUBLISHED),
        one["temperature_k"],
        1e-2,
    )
    np.testing.assert_allclose(
        effective_sigma(one, name, PUBLISHED, True),
        abs(ft - pt) * one["temperature_error_k"],
        rtol=1e-12,
    )
    one["temperature_error_k"][:] = np.nan
    assert np.isnan(effective_sigma(one, name, PUBLISHED, True)[0])
    one["mgo"][:] = False
    one["temperature_error_k"][:] = 0
    assert effective_sigma(one, name, PUBLISHED, True)[0] == pytest.approx(1e6)


@pytest.mark.parametrize("failure", ["rank", "bound", "convergence", "dof"])
def test_unreliable_covariance_rejected(failure):
    result = SimpleNamespace(
        success=True, active_mask=np.zeros(2), jac=np.eye(2), fun=np.ones(3)
    )
    count = 3
    if failure == "rank":
        result.jac[:] = 1
    elif failure == "bound":
        result.active_mask[0] = 1
    elif failure == "convergence":
        result.success = False
    else:
        count = 2
    with pytest.raises(ValueError):
        conditional_covariance(result, np.ones(2), count, "effective_errors")


def test_reconstruction_artifacts_covariance_and_original_inputs():
    summary, derived = reconstruct()
    stored = json.loads((OUT / "summary.json").read_text(encoding="utf-8"))
    assert summary["status"] == "conditional_reconstruction_not_original_fit_recovered"
    assert summary["original_csv_sha256"] == stored["original_csv_sha256"]
    for relative, digest in summary["original_csv_sha256"].items():
        assert hashlib.sha256((ROOT / relative).read_bytes()).hexdigest() == digest
    original, data, _ = read_data()
    for model, result in summary["results"].items():
        p, _, _ = pressure_column(data, model)
        np.testing.assert_array_equal(p[:15], data["pressure_gpa"][:15])
        for selection, fits in result["fits"].items():
            for mode, fitted in fits.items():
                saved = stored["results"][model]["fits"][selection][mode]
                assert fitted["solver_success"]
                assert fitted["weighted_row_count"] == saved["weighted_row_count"]
                np.testing.assert_allclose(
                    fitted["parameters"], saved["parameters"], rtol=2e-6, atol=2e-6
                )
                np.testing.assert_allclose(
                    fitted["covariance"], saved["covariance"], rtol=1e-4, atol=1e-6
                )
                cov = np.array(fitted["covariance"])
                assert np.all(np.linalg.eigvalsh(cov) > 0)
                np.testing.assert_allclose(
                    np.diag(cov), np.array(fitted["standard_errors"]) ** 2
                )
                assert len(cov) == len(fitted["free_parameter_names"])
                if mode == "effective_errors":
                    assert fitted["scaled_parameter_change"] < 1e-7
                    assert fitted["covariance_scale"] >= 1
                for stage in fitted["initial_thermal_stage"]:
                    assert len(stage["standard_errors"]) == 2
                    assert np.all(np.linalg.eigvalsh(stage["covariance"]) > 0)
    with (OUT / "pressures.csv").open(newline="") as stream:
        check_rows(
            list(csv.DictReader(stream)),
            derived,
            {
                "reconstructed_pressure_gpa",
                "pressure_shift_gpa",
                "conditional_pressure_error_gpa",
                "pressure_temperature_covariance_gpa_k",
                "published_fe_residual_gpa",
            },
        )
    assert len(derived) == 116 * 3
    for row in derived:
        source = original[15 + int(row["source_row"]) - 1]
        assert row["printed_pressure_gpa"] == source["pressure_gpa"]
        assert row["printed_pressure_error_gpa"] == source["pressure_error_gpa"]
        if row["source_row"] == "76":
            assert row["conditional_pressure_error_gpa"] == ""
    var = summary["results"]["speziale_variable_q_debye"]
    cold = var["fits"]["cold"]["unweighted"]
    np.testing.assert_allclose(
        cold["parameters"], [22.806277, 128.509389, 6.286870], rtol=2e-6
    )
    assert var["published_fe"]["cold_bm3"]["rmse_gpa"] < 1
    # Calibration fixes much of the cold mismatch, but does not identify the
    # source thermal fit. Never turn this conditional result into source parity.
    assert var["published_fe"]["heated"]["rmse_gpa"] > 6
    assert var["fits"]["thermal_all"]["unweighted"]["parameters"][3] > 1.8
