"""Peritheos: thermodynamic equations of state calculations."""

from peritheos.catalog import (
    RangeQuery,
    RangeSemantics,
    ValidationStatus,
    get_eos_record,
    get_material,
    list_eos_records,
    list_materials,
    search_eos_records,
    search_materials,
)
from peritheos.eosmat import (
    EOSMAT_FORMAT,
    EOSMAT_FORMAT_VERSION,
    eosmat_schema,
    get_material_document,
    list_material_documents,
    load_eosmat,
    save_eosmat,
    validate_eosmat_document,
)
from peritheos.errors import (
    ConfigurationError,
    EosError,
    EosmatError,
    EosNumericalError,
    EosValidationError,
    FitEosNumericalError,
    FitEosValidationError,
    FitError,
    FitNumericalError,
    FitValidationError,
    MaterialError,
    MaterialLookupError,
    NumericalError,
    PeritheosError,
    UnsupportedOperationError,
    ValidationError,
)
from peritheos.materials import (
    EOSRecord,
    Material,
    material_from_dict,
)
from peritheos.uncertainty import (
    EOSUncertainty,
    ParameterUncertainty,
    PredictionUncertainty,
)

__version__ = "0.6.0"

__all__ = [
    "ConfigurationError",
    "EOSMAT_FORMAT",
    "EOSMAT_FORMAT_VERSION",
    "EOSUncertainty",
    "EosError",
    "EosNumericalError",
    "EosValidationError",
    "EosmatError",
    "FitError",
    "FitEosNumericalError",
    "FitEosValidationError",
    "FitNumericalError",
    "FitValidationError",
    "MaterialError",
    "MaterialLookupError",
    "NumericalError",
    "ParameterUncertainty",
    "EOSRecord",
    "Material",
    "PredictionUncertainty",
    "RangeQuery",
    "RangeSemantics",
    "PeritheosError",
    "UnsupportedOperationError",
    "ValidationError",
    "ValidationStatus",
    "__version__",
    "eosmat_schema",
    "get_eos_record",
    "get_material",
    "get_material_document",
    "list_eos_records",
    "list_materials",
    "list_material_documents",
    "load_eosmat",
    "material_from_dict",
    "save_eosmat",
    "search_eos_records",
    "search_materials",
    "validate_eosmat_document",
]
