"""Peritheos: thermodynamic equations of state calculations."""

from peritheos.eosmat import (
    EOSMAT_FORMAT,
    EOSMAT_FORMAT_VERSION,
    eosmat_schema,
    get_eos_record_document,
    get_material_document,
    list_eos_record_documents,
    list_material_documents,
    load_eosmat,
    save_eosmat,
    validate_eosmat_document,
    validate_pressure_calibration_references,
)
from peritheos.errors import (
    ConfigurationError,
    EosError,
    EosmatError,
    EosNumericalError,
    EosValidationError,
    FitEosNumericalError,
    FitEosValidationError,
    FitError,
    FitNumericalError,
    FitValidationError,
    MaterialError,
    MaterialLookupError,
    NumericalError,
    PeritheosError,
    UnsupportedOperationError,
    ValidationError,
)
from peritheos.materials import (
    EOSRecord,
    Material,
    get_eos_record,
    get_material,
    list_eos_records,
    list_materials,
    material_from_dict,
)
from peritheos.pressure_calibrations import (
    RubyFluorescenceCalibration,
    XrdPressureRecalculation,
    get_pressure_calibration,
    get_pressure_calibration_document,
    list_pressure_calibrations,
    list_xrd_pressure_standards,
    pressure_calibration_library,
    recalculate_ruby_pressure,
    recalculate_ruby_to_xrd_pressure,
    xrd_standard_pressure,
)
from peritheos.uncertainty import (
    EOSUncertainty,
    ParameterUncertainty,
    PredictionUncertainty,
)

__version__ = "0.6.0"

__all__ = [
    "ConfigurationError",
    "EOSMAT_FORMAT",
    "EOSMAT_FORMAT_VERSION",
    "EOSUncertainty",
    "EosError",
    "EosNumericalError",
    "EosValidationError",
    "EosmatError",
    "FitError",
    "FitEosNumericalError",
    "FitEosValidationError",
    "FitNumericalError",
    "FitValidationError",
    "MaterialError",
    "MaterialLookupError",
    "NumericalError",
    "ParameterUncertainty",
    "EOSRecord",
    "Material",
    "PredictionUncertainty",
    "RubyFluorescenceCalibration",
    "XrdPressureRecalculation",
    "PeritheosError",
    "UnsupportedOperationError",
    "ValidationError",
    "__version__",
    "eosmat_schema",
    "get_eos_record",
    "get_eos_record_document",
    "get_material",
    "get_material_document",
    "get_pressure_calibration",
    "get_pressure_calibration_document",
    "list_eos_record_documents",
    "list_eos_records",
    "list_materials",
    "list_material_documents",
    "list_pressure_calibrations",
    "list_xrd_pressure_standards",
    "load_eosmat",
    "material_from_dict",
    "pressure_calibration_library",
    "recalculate_ruby_pressure",
    "recalculate_ruby_to_xrd_pressure",
    "save_eosmat",
    "validate_eosmat_document",
    "validate_pressure_calibration_references",
    "xrd_standard_pressure",
]
