"""Generate the index of standalone literature and source-audit reports."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "docs" / "literature-reproductions"
OUTPUT_PATH = ROOT / "docs" / "source-audits.md"


def _title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    raise ValueError(f"{path.relative_to(ROOT)} has no level-one heading")


def render_index() -> str:
    reports = sorted(
        ((_title(path), path) for path in REPORTS_DIR.glob("*.md")),
        key=lambda item: (item[0].casefold(), item[1].name),
    )
    lines = [
        "# Source audits and literature reproductions",
        "",
        "This index exposes every standalone investigation used to decide whether a",
        "published equation of state is executable, directly refittable, qualified,",
        "deferred, or excluded. Use the [paper investigation",
        "ledger](paper-investigation-ledger.md) for paper-level coverage and the",
        "[primary EOS refit validation](primary-eos-refits.md) for record-level fit",
        "outcomes. The older [consolidated reproduction",
        "record](literature-reproductions.md) contains additional investigations that",
        "predate the standalone-report structure.",
        "",
        "A source-reported parameterization can remain scientifically usable when its",
        "row-level inputs are unavailable. In that case the linked report documents",
        "what was searched, what can be reproduced independently, and why the record",
        "is classified as not directly refittable rather than inventing observations.",
        "",
        f"The current collection contains {len(reports)} standalone reports.",
        "",
        "<!-- Generated by scripts/generate_source_audit_index.py; do not edit the table manually. -->",
        "",
        "| Investigation | Report |",
        "|---|---|",
    ]
    for title, path in reports:
        relative = path.relative_to(ROOT / "docs").as_posix()
        safe_title = title.replace("|", "\\|")
        lines.append(f"| {safe_title} | [`{path.name}`]({relative}) |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/source-audits.md is not current",
    )
    args = parser.parse_args()
    expected = render_index()
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            raise SystemExit(
                "docs/source-audits.md is stale; run "
                "python scripts/generate_source_audit_index.py"
            )
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
